name: custom-lints

on:
  pull_request:
  push:
    branches: [main]

jobs:
  dylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-04-16
          components: rustc-dev, llvm-tools-preview

      - name: Install Dylint tools
        run: cargo install cargo-dylint dylint-link --locked

      - name: Run custom lint and fail on findings
        run: DYLINT_RUSTFLAGS="-D test_linting" cargo dylint --path test_linting --workspace -- --all-targets
